from .basic_cnns import basic_cnn, basic_cnn_pool
from .basic_cnns_mctc import basic_cnn_segm_sigmoid, basic_cnn_segm_logsoftmax, basic_cnn_segm_blank_logsoftmax
from .basic_cnns_mctc import deep_cnn_segm_sigmoid
